import type { FileData } from "../src/tree";

/** A real markdown page: has `filePath` and a `relativePath` with the original file name. */
export function page(
  slug: string,
  relativePath: string,
  frontmatter: Record<string, unknown> = {},
  extra: Record<string, unknown> = {},
): FileData {
  const stem = relativePath.split("/").pop()!.replace(/\.md$/, "");
  return {
    slug,
    filePath: `content/${relativePath}`,
    relativePath,
    frontmatter: { title: stem, ...frontmatter },
    ...extra,
  };
}

/** A folder page generated by the folder-page plugin: no `filePath`, title = directory name. */
export function virtualFolder(slug: string, title: string): FileData {
  return { slug, relativePath: `${slug}.md`, frontmatter: { title } };
}

export function site(): FileData[] {
  return [
    page("index", "index.md", { title: "Home" }),
    page("docs/index", "docs/index.md", { title: "Documentation" }),
    page("docs/01-intro", "docs/01 Intro.md", { title: "Intro" }),
    page("docs/02-setup", "docs/02 Setup.md", { title: "Setup" }),
    page("docs/03-advanced", "docs/03 Advanced.md"),
    virtualFolder("docs/guides/index", "Guides"),
    page("docs/guides/alpha", "docs/Guides/Alpha.md", { title: "Alpha" }),
    page("docs/guides/beta", "docs/Guides/Beta.md", { title: "Beta", navOrder: 1 }),
    page("docs/hidden", "docs/Hidden.md", { title: "Hidden", navHide: true }),
    virtualFolder("blog/index", "Blog"),
    page(
      "blog/first",
      "Blog/First.md",
      { title: "First post" },
      { dates: { created: new Date("2024-01-01"), modified: new Date("2025-06-01") } },
    ),
    page(
      "blog/second",
      "Blog/Second.md",
      { title: "Second post" },
      { dates: { created: new Date("2025-01-01"), modified: new Date("2025-02-01") } },
    ),
    page("blog/undated", "Blog/Undated.md", { title: "Undated post" }),
    page("orte/huettendorf", "Orte/Hüttendorf.md", { title: "Hüttendorf" }),
    page("archive/index", "archive/index.md", { title: "Archive", navHide: true }),
    page("archive/old", "archive/Old.md", { title: "Old" }),
    page("private/secret", "private/Secret.md", { title: "Secret" }),
    page("about-hidden", "About Hidden.md", { title: "About" }, { unlisted: true }),
    page("draft-page", "Draft.md", { title: "Draft", draft: true }),
    virtualFolder("tags/index", "Tags"),
    { slug: "tags/foo", frontmatter: { title: "Tag: foo" } },
    { slug: "404", frontmatter: { title: "Not found" } },
  ];
}
