/**
 * Cooperation with quartz-multilanguage. Its transformer stores
 * `fileData.multilanguage = { lang, baseSlug, … }` on every Markdown page, where `baseSlug` is
 * the slug without the language folder or suffix (`en/docs/setup` and `docs/setup.en` both
 * become `docs/setup`; frontmatter-detected and default-language pages keep their slug). A
 * language tree places pages by `baseSlug`, so every detection strategy yields the same
 * structure, while links keep pointing at the real slugs.
 *
 * Pages generated by other plugins (folder pages, tag pages) carry no language. They are
 * assigned through the directory mapping learnt from the real pages next to them.
 */
export type FileData = Record<string, unknown>;

export interface LanguageIndex {
  /** Language codes found on the pages, in first-seen order. Empty without quartz-multilanguage. */
  languages: string[];
  /** Slug directory → language → base directory (`en/docs` → `en` → `docs`). */
  dirs: Map<string, Map<string, string>>;
}

/** Where a file sits in the tree of one language; `lang` is undefined for language-neutral files. */
export interface Placement {
  lang?: string;
  /**
   * How much the placement can be trusted when two files claim the same key: `2` for a language
   * taken from a folder, suffix or frontmatter, `1` for the default language, `0` for a
   * generated page placed through its directory, or a language-neutral one.
   */
  rank: 0 | 1 | 2;
  /** Language-neutral slug used to place the file in the tree, e.g. `docs/setup`. */
  key: string;
}

interface MultilanguageData {
  lang: string;
  baseSlug: string;
  source?: string;
}

function multilanguageOf(data: FileData): MultilanguageData | undefined {
  const ml = data.multilanguage;
  if (ml === null || typeof ml !== "object") return undefined;
  const { lang, baseSlug, source } = ml as Record<string, unknown>;
  if (typeof lang !== "string" || !lang || typeof baseSlug !== "string" || !baseSlug) {
    return undefined;
  }
  return {
    lang: lang.toLowerCase(),
    baseSlug,
    ...(typeof source === "string" ? { source } : {}),
  };
}

function dirSegments(slug: string): string[] {
  return slug.split("/").slice(0, -1);
}

function join(dir: string, name: string): string {
  return dir ? `${dir}/${name}` : name;
}

const cache = new WeakMap<object, LanguageIndex>();

/** Cached per `allFiles` identity, like the tree. */
export function languageIndex(allFiles: FileData[]): LanguageIndex {
  const hit = cache.get(allFiles);
  if (hit) return hit;
  const languages: string[] = [];
  const dirs = new Map<string, Map<string, string>>();
  for (const data of allFiles) {
    const ml = multilanguageOf(data);
    const slug = typeof data.slug === "string" ? data.slug : "";
    if (!ml || !slug) continue;
    if (!languages.includes(ml.lang)) languages.push(ml.lang);
    const slugDirs = dirSegments(slug);
    const baseDirs = dirSegments(ml.baseSlug);
    // A language folder is stripped at the front; a suffix leaves the directories alone.
    const offset = slugDirs.length - baseDirs.length;
    if (offset < 0 || slugDirs.slice(offset).join("/") !== baseDirs.join("/")) continue;
    for (let i = offset; i <= slugDirs.length; i++) {
      const slugDir = slugDirs.slice(0, i).join("/");
      let perLang = dirs.get(slugDir);
      if (!perLang) {
        perLang = new Map();
        dirs.set(slugDir, perLang);
      }
      if (!perLang.has(ml.lang)) perLang.set(ml.lang, baseDirs.slice(0, i - offset).join("/"));
    }
  }
  const index = { languages, dirs };
  cache.set(allFiles, index);
  return index;
}

/** Every language tree a file belongs to, with its key there. */
export function placements(data: FileData, index: LanguageIndex): Placement[] {
  const slug = typeof data.slug === "string" ? data.slug : "";
  const ml = multilanguageOf(data);
  if (ml) return [{ lang: ml.lang, key: ml.baseSlug, rank: ml.source === "default" ? 1 : 2 }];
  const name = slug.split("/").pop() ?? slug;
  const mapped = index.dirs.get(dirSegments(slug).join("/"));
  if (!mapped || mapped.size === 0) return [{ key: slug, rank: 0 }];
  return [...mapped].map(([lang, dir]) => ({ lang, key: join(dir, name), rank: 0 as const }));
}

/** The placement of a file in one language tree (or its language-neutral placement). */
export function placementIn(
  data: FileData,
  index: LanguageIndex,
  lang: string | undefined,
): Placement | undefined {
  const all = placements(data, index);
  if (lang === undefined) return { key: typeof data.slug === "string" ? data.slug : "", rank: 0 };
  return all.find((p) => p.lang === lang) ?? all.find((p) => p.lang === undefined);
}

function primary(locale: string | undefined): string | undefined {
  return locale?.toLowerCase().split(/[-_]/)[0];
}

/**
 * Language of the page being rendered: its own, the one of the directory it sits in, and for
 * pages that belong to several or none, the site's locale if it names one of them.
 */
export function languageOfPage(
  data: FileData,
  index: LanguageIndex,
  siteLocale: string | undefined,
): string | undefined {
  if (index.languages.length === 0) return undefined;
  const langs = placements(data, index)
    .map((p) => p.lang)
    .filter((l): l is string => l !== undefined);
  const candidates = langs.length > 0 ? langs : index.languages;
  const site = primary(siteLocale);
  return candidates.find((l) => primary(l) === site) ?? candidates[0];
}

/** Locale for UI strings and sorting: the site's locale when it is this language, else the code. */
export function localeFor(lang: string, siteLocale: string | undefined): string {
  return primary(siteLocale) === primary(lang) && siteLocale ? siteLocale : lang;
}
